{{- if (hasKey .Values.controllerManager "create" | ternary .Values.controllerManager.create true) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  {{- if eq .Values.appendReleaseSuffix true}}
  name: function-mesh-controller-manager-{{.Release.Name }}
  {{- else }}
  name: function-mesh-controller-manager
  {{- end }}
  labels:
    app.kubernetes.io/name: {{ template "function-mesh-operator.name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: controller-manager
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+"  "_" }}
spec:
  replicas: {{ .Values.controllerManager.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "function-mesh-operator.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: controller-manager
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ template "function-mesh-operator.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: controller-manager
    spec:
    {{- if .Values.controllerManager.serviceAccount }}
    serviceAccount: {{ .Values.controllerManager.serviceAccount }}
    {{- end }}
    {{- if .Values.imagePullSecrets }}
    imagePullSecrets:
  {{ toYaml .Values.imagePullSecrets | indent 6 }}
  {{- end }}
  containers:
    - name: function-mesh-operator
      image: {{ .Values.operatorImage }}
      imagePullPolicy: {{ .Values.imagePullPolicy | default "IfNotPresent" }}
      {{- if .Values.controllerManager.resources }}
      resources:
  {{ toYaml .Values.controllerManager.resources | indent 12 }}
  {{- end }}
command:
  - /usr/local/bin/function-mesh-controller-manager
  {{- if .Values.controllerManager.selector }}
  {{- $label := join "," .Values.controllerManager.selector }}
          - -selector={{ $label }}
          {{- end }}
        env:
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
  {{- if eq .Values.appendReleaseSuffix true}}
  - name: HELM_RELEASE
    value: {{ .Release.Name }}
  {{- end }}
  {{- with .Values.controllerManager.nodeSelector }}
nodeSelector:
  {{ toYaml . | indent 8 }}
  {{- end }}

  {{- with .Values.controllerManager.affinity }}
affinity:
  {{ toYaml . | indent 8 }}
  {{- end }}

  {{- with .Values.controllerManager.tolerations }}
tolerations:
  {{ toYaml . | indent 8 }}
  {{- end }}

  {{- if .Values.controllerManager.priorityClassName }}
priorityClassName: {{ .Values.controllerManager.priorityClassName }}
  {{- end }}
  {{- end }}