
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /mutate-cloud-streamnative-io-streamnative-io-v1alpha1-sink
  failurePolicy: Fail
  name: msink.kb.io
  rules:
  - apiGroups:
    - cloud.streamnative.io.streamnative.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - sinks
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /mutate-cloud-streamnative-io-streamnative-io-v1alpha1-source
  failurePolicy: Fail
  name: msource.kb.io
  rules:
  - apiGroups:
    - cloud.streamnative.io.streamnative.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - sources

---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /validate-cloud-streamnative-io-streamnative-io-v1alpha1-function
  failurePolicy: Fail
  name: vfunction.kb.io
  rules:
  - apiGroups:
    - cloud.streamnative.io.streamnative.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - functions
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /validate-cloud-streamnative-io-streamnative-io-v1alpha1-function
  failurePolicy: Fail
  name: vfunction.kb.io
  rules:
  - apiGroups:
    - cloud.streamnative.io.streamnative.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - functions
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /validate-cloud-streamnative-io-streamnative-io-v1alpha1-sink
  failurePolicy: Fail
  name: vsink.kb.io
  rules:
  - apiGroups:
    - cloud.streamnative.io.streamnative.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - sinks
