# permissions for end users to edit functionmeshes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: functionmesh-editor-role
rules:
- apiGroups:
  - cloud.streamnative.io
  resources:
  - functionmeshes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloud.streamnative.io
  resources:
  - functionmeshes/status
  verbs:
  - get
