# permissions for end users to view functionmeshes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: functionmesh-viewer-role
rules:
- apiGroups:
  - cloud.streamnative.io
  resources:
  - functionmeshes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cloud.streamnative.io
  resources:
  - functionmeshes/status
  verbs:
  - get
