# permissions for end users to view sinks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sink-viewer-role
rules:
- apiGroups:
  - cloud.streamnative.io
  resources:
  - sinks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cloud.streamnative.io
  resources:
  - sinks/status
  verbs:
  - get
