apiVersion: cloud.streamnative.io/v1alpha1
kind: Function
metadata:
  name: function-sample
spec:
  className: org.apache.pulsar.functions.api.examples.ExclamationFunction
  sourceType: java.lang.String
  sinkType: java.lang.String

  forwardSourceMessageProperty: true
  MaxPendingAsyncRequests: 1000
  replicas: 1
  maxReplicas: 5
  logTopic: persistent://public/default/logging-function-logs
  sources:
    - persistent://public/default/source-topic1
  sink: persistent://public/default/sink-topic
  resources:
    cpu: "1.5"
    memory: 1.5G
  # each secret will be loaded ad an env variable from the `path` secret with the `key` in that secret in the name of `name`
  secretsMap:
    "name":
        path: "test-secret"
        key: "username"
    "pwd":
        path: "test-secret"
        key: "password"
  pulsar:
    pulsarConfig: "test-pulsar"
    #authConfig: "test-auth"
  java:
    jar: pulsar-functions-api-examples.jar
    jarLocation: public/default/nlu-test
  # to be delete & use admission hook
  clusterName: test
  autoAck: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-pulsar
data:
    webServiceURL: http://test-pulsar-broker.default.svc.cluster.local:8080
    brokerServiceURL: pulsar://test-pulsar-broker.default.svc.cluster.local:6650
#---
#apiVersion: v1
#kind: ConfigMap
#metadata:
#  name: test-auth
#data:
#  clientAuthenticationPlugin: "abc"
#  clientAuthenticationParameters: "xyz"
#  tlsTrustCertsFilePath: "uvw"
#  useTls: "true"
#  tlsAllowInsecureConnection: "false"
#  tlsHostnameVerificationEnable: "true"
---
apiVersion: v1
data:
  username: YWRtaW4=
  password: MWYyZDFlMmU2N2Rm
kind: Secret
metadata:
  name: test-secret
type: Opaque
