apiVersion: cloud.streamnative.io/v1alpha1
kind: FunctionMesh
metadata:
  name: functionmesh-sample
spec:
  functions:
    - name: ex1
      className: org.apache.pulsar.functions.api.examples.ExclamationFunction
      sourceTypeClass: java.lang.String
      sinkTypeClass: java.lang.String
      parallelism: 3
      logTopic: persistent://public/default/logging-function-logs
      sources:
        - persistent://public/default/source-topic1
      sink: persistent://public/default/sink-topic
      pulsar:
        pulsarConfig: "mesh-test-pulsar"
      java:
        jar: pulsar-functions-api-examples.jar
        jarLocation: public/default/nlu-test
    - name: ex2
      className: org.apache.pulsar.functions.api.examples.ExclamationFunction
      sourceTypeClass: java.lang.String
      sinkTypeClass: java.lang.String
      parallelism: 2
      logTopic: persistent://public/default/logging-function-logs
      sources:
        - persistent://public/default/source-topic1
      sink: persistent://public/default/sink-topic
      pulsar:
        pulsarConfig: "mesh-test-pulsar"
      java:
        jar: pulsar-functions-api-examples.jar
        jarLocation: public/default/nlu-test
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mesh-test-pulsar
data:
  webServiceURL: http://test-pulsar-broker.default.svc.cluster.local:8080
  brokerServiceURL: pulsar://test-pulsar-broker.default.svc.cluster.local:6650

