apiVersion: cloud.streamnative.io/v1alpha1
kind: Source
metadata:
  name: source-sample
spec:
  className: org.apache.pulsar.io.debezium.mongodb.DebeziumMongoDbSource
  sourceType: org.apache.pulsar.common.schema.KeyValue
  sinkType: org.apache.pulsar.common.schema.KeyValue
  replicas: 1
  sink: persistent://public/default/destination
  sourceConfig:
    mongodb.hosts: rs0/mongo-dbz-0.mongo.default.svc.cluster.local:27017,rs0/mongo-dbz-1.mongo.default.svc.cluster.local:27017,rs0/mongo-dbz-2.mongo.default.svc.cluster.local:27017
    mongodb.name: dbserver1
    mongodb.user: debezium
    mongodb.password: dbz
    mongodb.task.id: "1"
    database.whitelist: inventory
    pulsar.service.url: pulsar://test-pulsar-broker.default.svc.cluster.local:6650
  pulsar:
    pulsarConfig: "test-source"
  java:
    jar: connectors/pulsar-io-debezium-mongodb-2.6.1.nar
    jarLocation: "" # use pulsar provided connectors
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-source
data:
  webServiceURL: http://test-pulsar-broker.default.svc.cluster.local:8080
  brokerServiceURL: pulsar://test-pulsar-broker.default.svc.cluster.local:6650
