apiVersion: cloud.streamnative.io/v1alpha1
kind: Function
metadata:
  name: function-sample
spec:
  className: org.apache.pulsar.functions.api.examples.ExclamationFunction
  sourceTypeClass: java.lang.String
  sinkTypeClass: java.lang.String
  replicas: 1
  maxReplicas: 5
  logTopic: persistent://public/default/logging-function-logs
  sources:
    - persistent://public/default/source-topic1
  sink: persistent://public/default/sink-topic
  pulsar:
    pulsarConfig: "test-pulsar"
  java:
    jar: pulsar-functions-api-examples.jar
    jarLocation: public/default/nlu-test
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-pulsar
data:
    webServiceURL: http://test-pulsar-broker.default.svc.cluster.local:8080
    brokerServiceURL: pulsar://test-pulsar-broker.default.svc.cluster.local:6650
