apiVersion: compute.functionmesh.io/v1alpha1
kind: Function
metadata:
  name: py-function-zip-generic-sample
  namespace: default
spec:
  image: jiangpch/generic-runtime-python:v0.31.0
  className: myhttp
  forwardSourceMessageProperty: true
  maxPendingAsyncRequests: 1000
  replicas: 1
  input:
    topics:
    - persistent://public/default/py-generic-zip-input
    typeClassName: string
  output:
    topic: persistent://public/default/py-generic-zip-output
    typeClassName: bytes
  resources:
    requests:
      cpu: 500m
      memory: 0.5G
    limits:
      cpu: 500m
      memory: 0.5G
  pulsar:
    pulsarConfig: "test-py-pulsar"
    tlsConfig:
      enabled: false
      allowInsecure: true
      hostnameVerification: true
  python:
    py: httppy.zip
    pyLocation: function://public/default/py-zip
  clusterName: test
  autoAck: true
  useGenericRuntime: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-py-pulsar
data:
  webServiceURL: http://sn-platform-pulsar-broker.default.svc.cluster.local:8080
  brokerServiceURL: pulsar://sn-platform-pulsar-broker.default.svc.cluster.local:6650
