name: Function-Mesh Release

on:
  release:
    types: [created]

jobs:
  upload:
    name: Upload Release files
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        env:
          VERSION: ${{ github.event.release.tag_name }}
          DOCKER_REPO: "${GITHUB_ACTOR}/function-mesh"
        with:
          images: "$DOCKER_REPO"
          tag-latest: true
          tag-semver: |
            {{github.event.release.tag_name}}

      - name: Set up GO 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go

      - name: setup kubebuilder 2.3.1
        uses: RyanSiu1995/kubebuilder-action@v1.1
        with:
          version: 2.3.1

      - name: build release
        id: build_release
        env:
          VERSION: ${{ github.event.release.tag_name }}
          DOCKER_REPO: ${GITHUB_ACTOR}
        run: |
          DOCKER_REPO=${GITHUB_ACTOR} make release
          DOCKER_REPO=${GITHUB_ACTOR} make docker-push

      - name: Publish docker image
        uses: docker/build-push-action@v2
        id: push_docker_image
        env:
          GITHUB_ACTOR: ${GITHUB_ACTOR}
        with:
          context: .
          file: ./operator.Dockerfile
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
